//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

#ifndef FONT_ARROWS_H
#define FONT_ARROWS_H

#include <avr/pgmspace.h>

static const unsigned char Arrows [] PROGMEM = {
// first row defines - FONTWIDTH, FONTHEIGHT, ASCII START CHAR, TOTAL CHARACTERS, FONT MAP WIDTH HIGH, FONT MAP WIDTH LOW (2,56 meaning 256)
	7, 14, 49, 2, 0, 14,
	0x00, 0x00, 0x00, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x08, 0x04, 0xFE, 0x04, 0x08, 0x00, 0x00, 0x04,
	0x08, 0x1F, 0x08, 0x04, 0x00, 0x00, 0x00, 0x00,
};

#define DOWN_ARROW	"1"
#define UP_ARROW	"2"

#endif